language: python
python:
 - "2.7"
install:
 - pip install -r ./utils/py_modules/requirements.txt
services:
 - mongodb
env:
 global:
  - py_env=test
  - NODE_ENV=test
before_script:
 - npm install
 - sleep 15
script:
 - DEBUG=countrygraph mocha test

